// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import ReasonModuleCss from "../../styles/Reason.module.css";

var styles = ReasonModuleCss;

function Reason(Props) {
  return React.createElement("div", {
              className: styles.container
            }, "REASON PAGE!");
}

var make = Reason;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
