// Generated by ReScript, PLEASE EDIT WITH CARE


function appToString(x) {
  switch (x) {
    case /* Messages */0 :
        return "Messages";
    case /* Crapchat */1 :
        return "Crapchat";
    case /* Bank */2 :
        return "Bank";
    case /* Home */3 :
        return "None";
    
  }
}

var apps = [
  /* Messages */0,
  /* Crapchat */1,
  /* Bank */2
];

export {
  appToString ,
  apps ,
  
}
/* No side effect */
