// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Smartphone$Reason from "../../components/Smartphone.bs.js";
import * as EggplantScreen$Reason from "../../components/EggplantScreen.bs.js";
import EggplantModuleCss from "../../styles/Eggplant.module.css";

var styles = EggplantModuleCss;

function Eggplant(Props) {
  return React.createElement("div", {
              className: styles.container
            }, React.createElement(Smartphone$Reason.make, {
                  children: React.createElement(EggplantScreen$Reason.make, {})
                }));
}

var make = Eggplant;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
