// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import AppModuleCss from "../styles/components/App.module.css";

var styles = AppModuleCss;

function App(Props) {
  var label = Props.label;
  var onClick = Props.onClick;
  return React.createElement("button", {
              className: styles.icon,
              onClick: onClick
            }, label);
}

var make = App;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
