// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button$Reason from "./Button.bs.js";
import AppModuleCss from "../styles/components/App.module.css";

var styles = AppModuleCss;

function App(Props) {
  var onClick = Props.onClick;
  var children = Props.children;
  return React.createElement("div", {
              className: styles.container
            }, React.createElement(Button$Reason.make, {
                  label: "Back",
                  onClick: onClick
                }), children);
}

var make = App;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
