// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import AppIconModuleCss from "../styles/components/AppIcon.module.css";

var styles = AppIconModuleCss;

function AppIcon(Props) {
  var label = Props.label;
  var onClick = Props.onClick;
  return React.createElement("button", {
              className: styles.icon,
              onClick: onClick
            }, label);
}

var make = AppIcon;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
