// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as App$Reason from "./App.bs.js";

function AppScreen(Props) {
  var onClick = Props.onClick;
  var app = Props.app;
  switch (app) {
    case /* Messages */0 :
        return React.createElement(App$Reason.make, {
                    onClick: onClick,
                    children: "No new messages"
                  });
    case /* Crapchat */1 :
        return React.createElement(App$Reason.make, {
                    onClick: onClick,
                    children: null
                  }, React.createElement("h1", undefined, "You have been banned for the following reasons:"), React.createElement("div", undefined, "Reeking of a not so quiet desperation"));
    case /* Bank */2 :
        return React.createElement(App$Reason.make, {
                    onClick: onClick,
                    children: "Balance: -$21.32"
                  });
    case /* Home */3 :
        return null;
    
  }
}

var make = AppScreen;

export {
  make ,
  
}
/* react Not a pure module */
