// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import ButtonModuleCss from "../styles/components/Button.module.css";

var styles = ButtonModuleCss;

function Button(Props) {
  var label = Props.label;
  var onClick = Props.onClick;
  return React.createElement("button", {
              className: styles.container,
              onClick: onClick
            }, label);
}

var make = Button;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
