// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Greetings(Props) {
  var name = Props.name;
  return React.createElement("button", undefined, "Hello " + (name + "!"));
}

var make = Greetings;

export {
  make ,
  
}
/* react Not a pure module */
