// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import SmartphoneModuleCss from "../styles/components/Smartphone.module.css";

var styles = SmartphoneModuleCss;

function Smartphone(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: styles.smartphone
            }, React.createElement("div", {
                  className: styles.content
                }, children));
}

var make = Smartphone;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
