// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import HomeModuleCss from "../styles/Home.module.css";

var styles = HomeModuleCss;

var appName = "WebCellz";

function Index(Props) {
  return React.createElement("div", {
              className: styles.container
            }, React.createElement("head", undefined, React.createElement("title", undefined, "WebCellz"), React.createElement("link", {
                      href: "/favicon.ico",
                      rel: "icon"
                    })), React.createElement("header", undefined, appName), "Cell2!");
}

var make = Index;

export {
  styles ,
  appName ,
  make ,
  
}
/* styles Not a pure module */
