// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "../node_modules/bs-platform/lib/es6/array.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Router from "next/router";
import * as Button$Reason from "../components/Button.bs.js";
import HomeModuleCss from "../styles/Home.module.css";

var styles = HomeModuleCss;

var macrosoft = "MacroSoft";

var eggplant = "Eggplant";

var googol = "Googol";

var appName = "WebCellz";

var webcellz = [
  {
    name: macrosoft,
    url: "https://www.youtube.com/watch?v=eywi0h_Y5_U"
  },
  {
    name: eggplant,
    url: "/eggplant"
  },
  {
    name: googol,
    url: "./googol"
  }
];

function Index(Props) {
  var router = Router.useRouter();
  return React.createElement(React.Fragment, undefined, React.createElement("head", undefined, React.createElement("title", undefined, "WebCellz"), React.createElement("link", {
                      href: "/favicon.ico",
                      rel: "icon"
                    })), React.createElement("div", {
                  className: styles.container
                }, React.createElement("header", undefined, appName), React.createElement("div", {
                      className: styles.title
                    }, "Welcome to WebCellz!"), React.createElement("div", {
                      className: styles.description
                    }, "Why pay thousands of dollars for a cell phone when you can use a WebCell for free?"), React.createElement("div", {
                      className: styles.description
                    }, "Choose your WebCell from the WebCellz below"), React.createElement("div", {
                      className: styles.buttons
                    }, $$Array.map((function (webcell) {
                            var url = webcell.url;
                            var label = webcell.name;
                            var onClick = function (param) {
                              return Curry._1(router.push, url);
                            };
                            return React.createElement(Button$Reason.make, {
                                        label: label,
                                        onClick: onClick,
                                        key: label
                                      });
                          }), webcellz))));
}

var make = Index;

export {
  styles ,
  macrosoft ,
  eggplant ,
  googol ,
  appName ,
  webcellz ,
  make ,
  
}
/* styles Not a pure module */
